spring:
  application:
    name: yiqi-spring-cloud-web-account-ribbon

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 9201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/