spring:
  application:
    name: yiqi-spring-cloud-web-account-feign

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 9302


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/

feign:
  hystrix:
    enabled: true